[project]
name = "python"
version = "0.1.0"
description = "Eds Sandbox python environment"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "rich-pixels>=3.0.1",
    "textual>=2.1.1",
    "textual-pyfiglet>=0.5.5",
]

[dependency-groups]
dev = [
    "textual-dev>=1.7.0",
]
